include theos/makefiles/common.mk

LIBRARY_NAME = AMBitlyManager
AMBitlyManager_FILES = AMBitlyManager.m ../BitlyConnection.m ../UIViewController+Additions.m ../BitlyPreferences.m
AMBitlyManager_INSTALL_PATH = /Library/ActionMenu/Plugins
AMBitlyManager_FRAMEWORKS = Foundation UIKit CoreGraphics
AMBitlyManager_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/library.mk